services:
  mcbot:
    build:
      context: ./mcbot
      dockerfile: Dockerfile
    container_name: mcbot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MC_CONTAINER_NAME: cobblemon_fabric_server
      MCBOT_ROLE_NAME: 마크봇
      READY_LOG_PATTERN: "Voice chat server started at port"
      READY_TIMEOUT_SECONDS: "600"
      STOP_TIMEOUT_SECONDS: "120"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mc-server:
    image: itzg/minecraft-server
    container_name: cobblemon_fabric_server
    tty: true
    stdin_open: true
    restart: "no"
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.1"
      TYPE: "FABRIC"
      DIFFICULTY: "peaceful"
      KEEP_INVENTORY: "true"
      
      # --- 성능 최적화---
      MEMORY: "12G"
      INIT_MEMORY: "2G"
      USE_AIKAR_FLAGS: "true"
      # --- 게임 설정 ---
      view-distance: 10
      simulation-distance: 10
      MOTD: "Cobblemon(Fabric Server)"
      
    volumes:
      - ./data:/data

