services:
  mcbot:
    build:
      context: ./mcbot
      dockerfile: Dockerfile
    container_name: mcbot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MC_CONTAINER_NAME: mc-server
      MCBOT_ROLE_NAME: 마크봇
      READY_TIMEOUT_SECONDS: "600"
      STOP_TIMEOUT_SECONDS: "120"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mc-server:
    image: itzg/minecraft-server
    container_name: mc-server
    tty: true
    stdin_open: true
    restart: "no"
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      UID: "1001"
      GID: "1001"
      VERSION: "1.20.1"
      TYPE: "FORGE"
      # DIFFICULTY: "peaceful"
      ENABLE_RCON: "true"
      RCON_CMDS_STARTUP: "gamerule keepInventory true"
      
      # --- 성능 최적화---
      MEMORY: "14G"
      INIT_MEMORY: "14G"
      USE_AIKAR_FLAGS: "true"
      # --- 게임 설정 ---
      view-distance: 8
      simulation-distance: 8
      MOTD: "SNOWY'S SERVER"
      
    volumes:
      - ./data:/data

    deploy:
      resources:
        limits:
          memory: 20g
